= ISO/TC211 Semantic Web Home

This repository contains the static website content of the https://def.isotc211.org, the home page of the https://www.iso.org[ISO]'s https://www.iso.org/committee/54904.html[Technical Committee 211]'s https://en.wikipedia.org/wiki/Semantic_Web[Semantic Web] content.

It also contains the web address redirection logic necissary to support persistent identifiers for ISO/TC211 semantic web objects that use the `https://def.isotc211.org/` namespace.

The ISO/TC211 is responsible for the standardization of 'Geographic information/Geomatics' information and produces a series of data models that are defined in the 19* series of ISO standards, for example, https://www.iso.org/standard/73118.html[ISO 19115-1:2014] which describes 'Geographic information — Metadata — Part 1: Fundamentals'.

Semantic Web objects defined for standards like ISO 19115 include _Code Sets_, for example 19115's https://def.isotc211.org/common/RoleCode[Role Code] codeset that defines "function performed by the responsible party [for catalogues spatial data]".

== Content

The folder `web/` contains the few static web pages rendered online at https://def.isotc211.org.

The folder `redirects/` contains the Apache server configuration for redirections of https://def.isotc211.org to the current resolving system, which is The https://defs.opengis.net/prez/[OGC's Rainbow Reference Data Platform].

== License and Use

The content of this repository is not expected to be relevant for use outside of the single deployment of https://def.isotc211.org, however, if you want to use any part, the applicable license is the https://creativecommons.org/licenses/by/4.0/[Creative Commons 4.0 BY license], a copy of the deed of which is contained in the file `LICENSE`.

== Contact

This repository and all work involving https://def.isotc211.org is managed by the https://committee.iso.org/sites/tc211/home/about/advisory-groups.html[ISO/TC211 _Advisory Group 6 - Group on Ontology Maintenance].
Please contact that group using the details at:

* https://github.com/ISO-TC211/GOM#contact
