---
layout: home
permalink: /
---
:page-liquid:


[.section]
== ISO TC-211's Semantic Web home

This web page is the root page of the `def.isotc211.org` namespace. The namespace is reserved for https://en.wikipedia.org/wiki/Semantic_Web[Semantic Web] versions of https://www.iso.org/committee/54904.html[TC-211] resources such as:

* https://www.w3.org/TR/skos-reference/[SKOS] data model vocabulary versions of 19* series standards' codelists
* https://www.w3.org/OWL/[OWL] ontology versions of 19* series standards' data models

[.section]
== Semantic Resources

Currently, as of May 2025, the only Semantic Web resources published by TC-211 are codelist vocabularies which are hosted for the TC-211 by the https://www.ogc.org[Open Geospatial Consortium (OGC)] on their reference data platform known as the https://defs.opengis.net/prez/['OGC Rainbow'].

See the catalogue of TC-211 resources at:

* https://defs.opengis.net/prez/catalogs

[.section]
== Persistent Identifiers

TC-211 Semantic Web resources all have persistent identifiers assigned to them in the form of https://en.wikipedia.org/wiki/Internationalized_Resource_Identifier[IRIs] - web page URL addresses.

You can go to the human-readable form of any TC-211 Semantic Web resource by just clicking on its IRI, for example, here is the IRI for ISO19115's _Role Code_ codelist:

link:/19115/-1/2018/CitationAndResponsiblePartyInformation/code/CI_RoleCode[http://def.isotc211.org/19115/-1/2018/CitationAndResponsiblePartyInformation/code/CI_RoleCode]

[.section]
== Maintenance

This web page and the TC's Semantic Web resources are managed by the TC's https://committee.iso.org/sites/tc211/home/about/advisory-groups.html[_Advisory Group 6: Group on Ontology Maintenance (GOM)_] and the OGC.

For any further information about these resources, please contact GOM whos contact details can be found at:

* https://github.com/ISO-TC211/GOM#contact
