name: build

on:
  push:
    branches:
      - '*'         # matches every branch
      - '*/*'       # matches every branch containing a single '/'
      - '!master'   # excludes master
      - '!staging'   # excludes master

jobs:
  build:
    name: Build site
    runs-on: ubuntu-latest
    steps:
      - name: Setup prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y curl make libxml2-dev libxslt-dev npm openssl
      - name: Setup snaps
        run: |
          sudo snap install aws-cli --classic
          sudo snap install node --classic --channel=10/stable
      - name: Use Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'
      - uses: actions/checkout@master
        with:
          submodules: true
      - name: Update gems
        run: |
          gem install bundler -v "~> 2"
          bundle install --jobs 4 --retry 3
      - name: Setup npm
        run: |
          npm install
      - name: Build site
        run: |
          make _site
